"""Build the sample-data cell used by steps 2-12 (and assets/sample.js, which
puts the same rows inside the browser exercises).

Run from the repo root:  python scripts/make_sample.py
"""
import csv, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
ACS_HDR = ["NAME", "B08301_001E", "B08301_018E", "B08301_018M", "B08301_019E",
           "B08301_021E", "state", "county", "tract", "block group"]
WALK_HDR = ["STATEFP", "COUNTYFP", "TRACTCE", "BLKGRPCE", "NatWalkInd",
            "D2A_Ranked", "D2B_Ranked", "D3B_Ranked", "D4A_Ranked", "TotPop"]


def write_full(acs, walk):
    """The whole county as Python literals, for the Jupyter interlude.

    A deliberate stopgap: the learner reaches the interlude having finished
    Unit 1 but not yet step 12, so they can run their pipeline over all 632
    block groups without needing the csv module first. Step 12 replaces it
    with the real files, and the size of this thing is the argument.
    """
    def literal(name, header, rows, cols):
        body = "\n".join("    " + json.dumps([r[c] for c in cols]) + "," for r in rows)
        return f"{name} = [\n    {json.dumps(header)},\n{body}\n]"

    text = ('"""Marion County, Indiana: every block group, as Python literals.\n\n'
            "Generated by scripts/make_sample.py -- do not hand-edit.\n\n"
            "This exists so the Jupyter interlude can run your Unit 1 pipeline over\n"
            "the whole county before you have met the csv module. In a notebook:\n\n"
            "    %run ../data/marion_full.py\n\n"
            "Step 12 reads data/*.csv properly, and retires this file. Note how\n"
            'much larger it is than the CSVs it duplicates -- that is the point.\n"""\n\n'
            + literal("acs_raw", ACS_HDR, acs, ACS_HDR) + "\n\n"
            + literal("walk_raw", WALK_HDR, walk, WALK_HDR) + "\n")
    (ROOT / "data/marion_full.py").write_text(text)
    print(f"wrote data/marion_full.py ({len(acs)} ACS rows, {len(walk)} walkability rows)")


def main():
    walk = list(csv.DictReader(open(ROOT / "data/walkability_marion.csv")))
    acs = list(csv.DictReader(open(ROOT / "data/acs_commute_marion.csv")))
    wl = {(r["TRACTCE"], r["BLKGRPCE"]): r for r in walk}
    key = lambda r: (r["tract"], r["block group"])

    # A teaching dozen: a spread of walkability plus every failure mode the
    # full dataset contains, so the early exercises meet the real data's edges.
    chosen, seen = [], set()
    for pick in (next(r for r in acs if r["B08301_018E"] == "-666666666"),
                 next(r for r in acs if r["B08301_001E"] == "0" and key(r) in wl),
                 next(r for r in acs if key(r) not in wl)):
        chosen.append(pick); seen.add(key(pick))
    spread = sorted((r for r in acs if key(r) in wl and key(r) not in seen),
                    key=lambda r: float(wl[key(r)]["NatWalkInd"]))
    for i in (0, 70, 170, 280, 400, 490, 560, len(spread) - 1):
        r = spread[i]
        if key(r) not in seen:
            chosen.append(r); seen.add(key(r))
    chosen.sort(key=lambda r: (r["tract"], int(r["block group"])))

    acs_rows = [ACS_HDR] + [[r[c] for c in ACS_HDR] for r in chosen]
    walk_rows = [[wl[key(r)][c] for c in WALK_HDR] for r in chosen if key(r) in wl]
    orphan = next(r for r in walk
                  if (r["TRACTCE"], r["BLKGRPCE"]) not in {key(a) for a in acs})
    walk_rows.append([orphan[c] for c in WALK_HDR])
    walk_rows.sort(key=lambda r: (r[2], int(r[3])))
    walk_rows = [WALK_HDR] + walk_rows

    def literal(name, rows):
        body = "\n".join("    " + json.dumps(r) + "," for r in rows)
        return f"{name} = [\n{body}\n]"

    text = ("# Sample rows, shaped exactly as the real data arrives.\n"
            "# The Census API returns a list of lists with a header row, all strings.\n"
            "# Step 13 replaces this cell with the full CSVs in data/.\n\n"
            + literal("acs_raw", acs_rows) + "\n\n"
            + literal("walk_raw", walk_rows) + "\n")

    (ROOT / "data/sample_rows.py").write_text(text)
    write_full(acs, walk)
    (ROOT / "assets/sample.js").write_text(
        "/* Generated by scripts/make_sample.py — do not hand-edit. */\n"
        "const SAMPLE = " + json.dumps(text) + ";\n")
    print(f"wrote data/sample_rows.py ({len(acs_rows)-1} ACS rows, "
          f"{len(walk_rows)-1} walkability rows) and assets/sample.js")


if __name__ == "__main__":
    main()
